In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
file_path = "/content/drive/MyDrive/Titanic_Dataset.csv"

In [ ]:
import pandas as pd
df = pd.read_csv(file_path)

In [ ]:
df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
dtypes: float64(2), int64(5), object(3)
memory usage: 69.7+ KB

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.describe(include= "object")

                       Name   Sex  Ticket
count                   891   891     891
unique                  891     2     681
top     Dooley, Mr. Patrick  male  347082
freq                      1   577       7

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
dtype: int64

PassengerId	Unique ID assigned to the passenger

Survived	Whether the passenger survived: 1 = Yes, 0 = No
Pclass	Passenger class: 1 = First, 2 = Second, 3 = Third
Name	Passenger's full name
Sex	Passenger's sex
Age	Passenger's age
SibSp	Number of siblings/spouses aboard the Titanic
Parch	Number of parents/children aboard
Ticket	Passenger's ticket number
Fare	Amount paid for the ticket

age is missing

In [ ]:
# handling missing values
df["Age"] = df["Age"].fillna(df["Age"].median())

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500

In [ ]:
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
df["Survived"].value_counts(normalize=True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

Explore relationships

In [ ]:
df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [ ]:
df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [ ]:
df.groupby("Survived")["Age"].mean()

Survived
0    30.028233
1    28.291433
Name: Age, dtype: float64

Create your first features

In [ ]:
#  Family Size

df["FamilySize"] = df["SibSp"] + df["Parch"] + 1

In [ ]:
# 4. IsAlone
# ---------------------------------------------------------

df["IsAlone"] = (df["FamilySize"] == 1).astype(int)
df["Child"] = (df["Age"] < 16).astype(int)

In [ ]:
df.groupby("FamilySize")["Survived"].mean()

FamilySize
1     0.303538
2     0.552795
3     0.578431
4     0.724138
5     0.200000
6     0.136364
7     0.333333
8     0.000000
11    0.000000
Name: Survived, dtype: float64

In [ ]:
df.groupby("IsAlone")["Survived"].mean()

IsAlone
0    0.505650
1    0.303538
Name: Survived, dtype: float64

In [ ]:
df.groupby("Child")["Survived"].mean()

Child
0    0.362624
1    0.590361
Name: Survived, dtype: float64

learn Name

In [ ]:
df["Title"] = df["Name"].str.extract(r",\s*([^.]*)\.")
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,FamilySize,IsAlone,Child,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,2,0,0,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,2,0,0,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,1,1,0,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,2,0,0,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,1,1,0,Mr
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,1,1,0,Mr
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,1,1,0,Mr
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,5,0,1,Master
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,3,0,0,Mrs
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,2,0,1,Mrs

Title potentially tells us something about:

gender
age
social status
marital status

In [ ]:
df.groupby("Title")["Survived"].mean()

Title
Capt            0.000000
Col             0.500000
Don             0.000000
Dr              0.428571
Jonkheer        0.000000
Lady            1.000000
Major           0.500000
Master          0.575000
Miss            0.697802
Mlle            1.000000
Mme             1.000000
Mr              0.156673
Mrs             0.792000
Ms              1.000000
Rev             0.000000
Sir             1.000000
the Countess    1.000000
Name: Survived, dtype: float64

In [ ]:
df["Title"].value_counts()

Title
Mr              517
Miss            182
Mrs             125
Master           40
Dr                7
Rev               6
Col               2
Mlle              2
Major             2
Ms                1
Mme               1
Don               1
Lady              1
Sir               1
Capt              1
the Countess      1
Jonkheer          1
Name: count, dtype: int64

In [ ]:
df.groupby("Title")["Survived"].agg(["count", "mean"])

              count      mean
Title
Capt              1  0.000000
Col               2  0.500000
Don               1  0.000000
Dr                7  0.428571
Jonkheer          1  0.000000
Lady              1  1.000000
Major             2  0.500000
Master           40  0.575000
Miss            182  0.697802
Mlle              2  1.000000
Mme               1  1.000000
Mr              517  0.156673
Mrs             125  0.792000
Ms                1  1.000000
Rev               6  0.000000
Sir               1  1.000000
the Countess      1  1.000000

In [ ]:
df["Surname"] = df["Name"].str.split(",").str[0]

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,FamilySize,IsAlone,Child,Title,Surname
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,2,0,0,Mr,Braund
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,2,0,0,Mrs,Cumings
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,1,1,0,Miss,Heikkinen
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,2,0,0,Mrs,Futrelle
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,1,1,0,Mr,Allen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,1,1,0,Rev,Montvila
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,1,1,0,Miss,Graham
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,4,0,0,Miss,Johnston
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,1,1,0,Mr,Behr
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,1,1,0,Mr,Dooley

In [ ]:
df["TicketGroupSize"]= df.groupby("Ticket")["PassengerId"].transform("count")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,FamilySize,IsAlone,Child,Title,Surname,FamilyGroup_titanic,SurnameGroupSize,TicketGroupSize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,2,0,0,Mr,Braund,161,2,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,2,0,0,Mrs,Cumings,161,1,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,1,1,0,Miss,Heikkinen,537,1,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,2,0,0,Mrs,Futrelle,161,2,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,1,1,0,Mr,Allen,537,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,1,1,0,Rev,Montvila,537,1,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,1,1,0,Miss,Graham,537,3,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,4,0,0,Miss,Johnston,29,2,2
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,1,1,0,Mr,Behr,537,1,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,1,1,0,Mr,Dooley,537,1,1

In [ ]:
df["TicketPrefix"] = (
    df["Ticket"]
    .str.replace(r"\d", "", regex=True)
    .str.replace(r"[./]", "", regex=True)
    .str.replace(" ", "", regex=True)
    .str.upper()
)

df["TicketPrefix"] = df["TicketPrefix"].replace("", "NONE")

In [ ]:
df.groupby("TicketPrefix")["Survived"].mean()

TicketPrefix
A            0.071429
AS           0.000000
C            0.400000
CA           0.341463
CASOTON      0.000000
FA           0.000000
FC           0.000000
FCC          0.800000
LINE         0.250000
NONE         0.384266
PC           0.650000
PP           0.666667
PPP          0.500000
SC           1.000000
SCA          0.000000
SCAH         0.500000
SCAHBASLE    1.000000
SCOW         0.000000
SCPARIS      0.454545
SOC          0.166667
SOP          0.000000
SOPP         0.000000
SOTONO       0.000000
SOTONOQ      0.133333
SP           0.000000
STONO        0.444444
SWPP         1.000000
WC           0.100000
WEP          0.333333
Name: Survived, dtype: float64

In [ ]:
df["FarePerPerson"] = (
    df["Fare"] / df["TicketGroupSize"]
)

In [ ]:
df["Child"] = (df["Age"] < 16).astype(int)

In [ ]:
df.groupby("Child")["Survived"].mean()

Child
0    0.362624
1    0.590361
Name: Survived, dtype: float64

In [ ]:
df["AgeGroup"] = pd.cut(
    df["Age"],
    bins=[0, 12, 18, 30, 50, 100],
    labels=[
        "Child",
        "Teenager",
        "YoungAdult",
        "Adult",
        "Senior"
    ]
)

In [ ]:
df.groupby("AgeGroup", observed=True)["Survived"].mean()

AgeGroup
Child         0.579710
Teenager      0.428571
YoungAdult    0.331096
Adult         0.423237
Senior        0.343750
Name: Survived, dtype: float64

In [ ]:
# mapping

df["Sex"] = df["Sex"].map({
    "male": 0,
    "female": 1
})

In [ ]:
df = pd.get_dummies(
    df,
    columns=["AgeGroup"],
    drop_first=True
)

In [ ]:
df = pd.get_dummies(
    df,
    columns=["TicketPrefix"],
    drop_first=True
)

In [ ]:
# Remove columns that we don't want directly in the model
df.drop(
    ["PassengerId", "Name", "Ticket", "Surname"],
    axis=1,
    inplace=True
)

In [ ]:
print(df.head())

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  FamilySize  IsAlone  \
0         0       3    0  22.0      1      0   7.2500           2        0
1         1       1    1  38.0      1      0  71.2833           2        0
2         1       3    1  26.0      0      0   7.9250           1        1
3         1       1    1  35.0      1      0  53.1000           2        0
4         0       3    0  35.0      0      0   8.0500           1        1

   Child  ...  TicketPrefix_SOC  TicketPrefix_SOP  TicketPrefix_SOPP  \
0      0  ...             False             False              False
1      0  ...             False             False              False
2      0  ...             False             False              False
3      0  ...             False             False              False
4      0  ...             False             False              False

   TicketPrefix_SOTONO  TicketPrefix_SOTONOQ  TicketPrefix_SP  \
0                False                 False            False
1                False                 False            False
2                False                 False            False
3                False                 False            False
4                False                 False            False

   TicketPrefix_STONO  TicketPrefix_SWPP  TicketPrefix_WC  TicketPrefix_WEP
0               False              False            False             False
1               False              False            False             False
2                True              False            False             False
3               False              False            False             False
4               False              False            False             False

[5 rows x 63 columns]