In [178]:
file_path = "Breast_Cancer.csv"

In [179]:
import pandas as pd
df = pd.read_csv(file_path)

In [180]:
df.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive

In [181]:
df.isna().sum()

Age                       0
Race                      0
Marital Status            0
T Stage                   0
N Stage                   0
6th Stage                 0
differentiate             0
Grade                     0
A Stage                   0
Tumor Size                0
Estrogen Status           0
Progesterone Status       0
Regional Node Examined    0
Reginol Node Positive     0
Survival Months           0
Status                    0
dtype: int64

In [182]:
df.describe()

,Age,Tumor Size,Regional Node Examined,Reginol Node Positive,Survival Months
count,4024.000000,4024.000000,4024.000000,4024.000000,4024.000000
mean,53.972167,30.473658,14.357107,4.158052,71.297962
std,8.963134,21.119696,8.099675,5.109331,22.921430
min,30.000000,1.000000,1.000000,1.000000,1.000000
25%,47.000000,16.000000,9.000000,1.000000,56.000000
50%,54.000000,25.000000,14.000000,2.000000,73.000000
75%,61.000000,38.000000,19.000000,5.000000,90.000000
max,69.000000,140.000000,61.000000,46.000000,107.000000

In [183]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4024 non-null   int64
 1   Race                    4024 non-null   str
 2   Marital Status          4024 non-null   str
 3   T Stage                 4024 non-null   str
 4   N Stage                 4024 non-null   str
 5   6th Stage               4024 non-null   str
 6   differentiate           4024 non-null   str
 7   Grade                   4024 non-null   str
 8   A Stage                 4024 non-null   str
 9   Tumor Size              4024 non-null   int64
 10  Estrogen Status         4024 non-null   str
 11  Progesterone Status     4024 non-null   str
 12  Regional Node Examined  4024 non-null   int64
 13  Reginol Node Positive   4024 non-null   int64
 14  Survival Months         4024 non-null   int64
 15  Status                  4024 non-null   str
dtypes: int64(5), str(11)
memory usage: 503.1 KB

In [184]:
df.columns

Index(['Age', 'Race', 'Marital Status', 'T Stage ', 'N Stage', '6th Stage',
       'differentiate', 'Grade', 'A Stage', 'Tumor Size', 'Estrogen Status',
       'Progesterone Status', 'Regional Node Examined',
       'Reginol Node Positive', 'Survival Months', 'Status'],
      dtype='str')

In [185]:
from sklearn.base import BaseEstimator, TransformerMixin

class FeatureEngineering(BaseEstimator, TransformerMixin):

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = X.copy()

        # Ratio of positive nodes
        X["positive_node_ratio"] = (
            X["Reginol Node Positive"] /
            X["Regional Node Examined"]
        )

        # Tumor size relative to positive nodes
        X["tumor_per_node"] = (
            X["Tumor Size"] /
            (X["Reginol Node Positive"] + 1)
        )

        # Age groups
        X["Age_Group"] = pd.cut(
            X["Age"],
            bins=[0, 40, 50, 60, 100],
            labels=["Young", "Middle", "Older", "Very_Older"]
        )

        # Tumor size groups
        X["Tumor_Size_Group"] = pd.cut(
            X["Tumor Size"],
            bins=[0, 20, 50, 100, float("inf")],
            labels=["Small", "Medium", "Large", "Very_Large"]
        )

        return X

In [186]:
X = df.drop(["Status", "Survival Months"], axis=1)
y = df["Status"]

In [187]:
from sklearn.pipeline import Pipeline

feature_pipeline = Pipeline([
    ("feature_engineering", FeatureEngineering())
])

In [188]:
feature_pipeline

Pipeline(steps=[('feature_engineering', FeatureEngineering())])

In [189]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4024 non-null   int64
 1   Race                    4024 non-null   str
 2   Marital Status          4024 non-null   str
 3   T Stage                 4024 non-null   str
 4   N Stage                 4024 non-null   str
 5   6th Stage               4024 non-null   str
 6   differentiate           4024 non-null   str
 7   Grade                   4024 non-null   str
 8   A Stage                 4024 non-null   str
 9   Tumor Size              4024 non-null   int64
 10  Estrogen Status         4024 non-null   str
 11  Progesterone Status     4024 non-null   str
 12  Regional Node Examined  4024 non-null   int64
 13  Reginol Node Positive   4024 non-null   int64
 14  Survival Months         4024 non-null   int64
 15  Status                  4024 non-null   str
dtypes: int64(5), str(11)
memory usage: 503.1 KB

In [190]:
numeric_features = [
    "Age",
    "Tumor Size",
    "Regional Node Examined",
    "Reginol Node Positive",
    "Survival Months"
]

In [191]:
categorical_features = [
    "Race",
    "Marital Status",
    "T Stage",
    "N Stage",
    "6th Stage",
    "differentiate",
    "Grade",
    "A Stage"
"Estrogen Status",
"Progesterone Status",
"Status"
]

In [192]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
numeric_pipeline = Pipeline([
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

trf1 = ColumnTransformer([
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features)
])

In [193]:
feature_engineering = FeatureEngineering()
print("Before:")
print(df.shape)

df_new = feature_engineering.fit_transform(df)

print("After:")
print(df_new.shape)

Before:
(4024, 16)
After:
(4024, 20)

In [194]:
df_new.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status,positive_node_ratio,tumor_per_node,Age_Group,Tumor_Size_Group
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive,0.041667,2.000000,Very_Older,Small
1,50,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive,0.357143,5.833333,Middle,Medium
2,58,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive,0.500000,7.875000,Older,Large
3,58,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive,0.500000,9.000000,Older,Small
4,47,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive,0.333333,20.500000,Middle,Medium

In [195]:
from sklearn.pipeline import Pipeline
pipe=Pipeline([
    ("feature_engineering", FeatureEngineering()),
    ("trans1",trf1)])

In [196]:
df.shape

(4024, 16)

In [197]:
df_new.shape

(4024, 20)